#!/bin/bash
# Created by Ivann LARUELLE / larueli on GitHub and Docker Hub
# kanboard-nonroot
if [ ! -d /var/www/html/data ]; then mkdir -m 770 /var/www/html/data; echo "---- Create data folder ----"; fi
if [ ! -d /var/www/html/plugins ]; then mkdir -m 770 /var/www/html/plugins; echo "---- Create plugins folder ----"; fi
if [ ! -d /var/www/ssl ]; then mkdir -m 770 /var/www/ssl; echo "---- Create SSL folder ----"; fi
if [ ! -f /var/www/kanboard.key  ] || [ ! -f /var/www/ssl/kanboard.crt ]
then
    echo "---- Create SSL keys ----"
    openssl req -x509 -nodes -newkey rsa:2048 -keyout /var/www/ssl/kanboard.key -out /var/www/ssl/kanboard.crt -subj '/C=GB/ST=London/L=London/O=Self Signed/OU=IT Department/CN=kanboard.org'
fi
chmod 770 /var/www/ssl/*
echo "---- Copying configmaps ----"
if [ -d /var/www/configmap ] && [ ! -z $(ls /var/www/configmap) ]; then cp -f /var/www/configmap/* /var/www/html/; fi
echo "---- Execute init scripts ----"
if [ -d /docker-entrypoint-initkanboard.d ]
then
	if [ ! -z $(ls /docker-entrypoint-initkanboard.d/) ]
	then
		for f in /docker-entrypoint-initkanboard.d/*; do
  		echo "     - Running $f"
  		bash "$f" -H 
		done
	fi
fi
echo "---- Launch server ----"
/usr/sbin/php-fpm7 -D
/usr/sbin/nginx -g 'daemon off;'
